FROM openjdk:17

ADD 5gla-public-rest-api/5gla-public-rest-api/target/5gla-public-rest-api.jar /opt/application/application.jar

RUN chmod 775 -R /opt/application && chown 1000:root -R /opt/application

USER 1000
EXPOSE 8080

WORKDIR /opt/application

ENTRYPOINT ["java","-jar","application.jar"]