app:
  version: '@project.version@'
  sensors:
    farm21:
      url: https://app.farm21.tech/api/v2/public
      username: ${FARM21_USERNAME}
      password: ${FARM21_PASSWORD}
      api-token: ${FARM21_API_TOKEN}
    soil-scout:
      url: https://soilscouts.fi/api/v1
      username: ${SOILSCOUT_USERNAME}
      password: ${SOILSCOUT_PASSWORD}
    agranimo:
      url: https://public-staging.agranimo.com
      username: ${AGRANIMO_USERNAME}
      password: ${AGRANIMO_PASSWORD}
    agvolution:
      url: https://api.agvolution.com
      username: ${AGVOLUTION_USERNAME}
      password: ${AGVOLUTION_PASSWORD}
    sensoterra:
      url: https://monitor.sensoterra.com/api/v3
      username: ${SENSOTERRA_USERNAME}
      password: ${SENSOTERRA_PASSWORD}
    micasense:
      image:
        path:
          base:
            url: ${IMAGE_PATH_BASE_URL}
  scheduled:
    data-import:
      cron: "0 */15 * * * *" # every 15 minutes
fiware:
  context-broker-url: ${CONTEXT_BROKER_URL}
logging:
  level:
    root: info
    de.app.fivegla: trace
one:
  microstream:
    storage-directory: ${MICROSTREAM_STORAGE_DIRECTORY}
    channel-count: 2

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
