app:
  version: '@project.version@'
  api-key: ${API_KEY}
  sensors:
    farm21:
      manufacturer: FARM21
      fiwareDeviceIdPrefix: "urn:5gla:dev:f21:"
      fiwareDeviceMeasurementIdPrefix: "urn:5gla:data:f21:"
      enabled: true
      url: https://app.farm21.tech/api/v2/public
      username: ${FARM21_USERNAME}
      password: ${FARM21_PASSWORD}
      apiToken: ${FARM21_API_TOKEN}
    soilscout:
      manufacturer: SOIL_SCOUT
      fiwareDeviceIdPrefix: "urn:5gla:dev:sosc:"
      fiwareDeviceMeasurementIdPrefix: "urn:5gla:data:sosc:"
      enabled: true
      url: https://soilscouts.fi/api/v1
      username: ${SOILSCOUT_USERNAME}
      password: ${SOILSCOUT_PASSWORD}
    agranimo:
      manufacturer: AGRANIMO
      fiwareDeviceIdPrefix: "urn:5gla:dev:agr:"
      fiwareDeviceMeasurementIdPrefix: "urn:5gla:data:agr:"
      enabled: true
      url: https://public-staging.agranimo.com
      username: ${AGRANIMO_USERNAME}
      password: ${AGRANIMO_PASSWORD}
    agvolution:
      manufacturer: AGVOLUTION
      fiwareDeviceIdPrefix: "urn:5gla:dev:agv:"
      fiwareDeviceMeasurementIdPrefix: "urn:5gla:data:agv:"
      enabled: true
      url: https://api.agvolution.com
      username: ${AGVOLUTION_USERNAME}
      password: ${AGVOLUTION_PASSWORD}
    sensoterra:
      manufacturer: SENSOTERRA
      fiwareDeviceIdPrefix: "urn:5gla:dev:st:"
      fiwareDeviceMeasurementIdPrefix: "urn:5gla:data:st:"
      enabled: true
      url: https://monitor.sensoterra.com/api/v3
      username: ${SENSOTERRA_USERNAME}
      password: ${SENSOTERRA_PASSWORD}
    micasense:
      manufacturer: MICASENSE
      fiwareDeviceIdPrefix: "urn:5gla:dev:ms:"
      fiwareDeviceMeasurementIdPrefix: "urn:5gla:data:ms:"
      enabled: true
      imagePathBaseUrl: ${IMAGE_PATH_BASE_URL}
    sentek:
      manufacturer: SENTEK
      fiwareDeviceIdPrefix: "urn:5gla:dev:sent:"
      fiwareDeviceMeasurementIdPrefix: "urn:5gla:data:sent:"
      enabled: true
      url: https://www.irrimaxlive.com/api
      apiToken: ${SENTEK_API_TOKEN}
    weenat:
      manufacturer: WEENAT
      fiwareDeviceIdPrefix: "urn:5gla:dev:wee:"
      fiwareDeviceMeasurementIdPrefix: "urn:5gla:data:wee:"
      enabled: true
      url: https://api-prod.weenat.com/api
      username: ${WEENAT_USERNAME}
      password: ${WEENAT_PASSWORD}
  scheduled:
    data-import:
      # Spring Boot uses ISO-8601 durations, https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/Duration.html#parse(java.lang.CharSequence)
      initial-delay: PT10S # 10 seconds
      delay: PT30M # 30 minutes
    daysInThePastForInitialImport: 3
  fiware:
    contextBrokerUrl: ${CONTEXT_BROKER_URL}
    subscriptions:
      enabled: true
      notificationUrls: ${NOTIFICATION_URLS}
    tenant: ${FIWARE_TENANT}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
logging:
  level:
    root: info
    de.app.fivegla: trace
one:
  microstream:
    storage-directory: ${MICROSTREAM_STORAGE_DIRECTORY}
    channel-count: 2

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
server:
  servlet:
    context-path: ${CONTEXT_PATH}
