app:
  version: '@project.version@'
  api-key: ${API_KEY}
  imagePathBaseUrl: ${IMAGE_PATH_BASE_URL}
  scheduled:
    data-import:
      # Spring Boot uses ISO-8601 durations, https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/Duration.html#parse(java.lang.CharSequence)
      initial-delay: PT10S # 10 seconds
      delay: PT30M # 30 minutes
    daysInThePastForInitialImport: 3
  fiware:
    contextBrokerUrl: ${CONTEXT_BROKER_URL}
    subscriptions:
      enabled: true
      notificationUrls: ${NOTIFICATION_URLS}
    tenant: ${FIWARE_TENANT}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
logging:
  level:
    root: info
    de.app.fivegla: trace
    java.net.http: debug
one:
  microstream:
    storage-directory: ${MICROSTREAM_STORAGE_DIRECTORY}
    channel-count: 2

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,agranimo,agvolution,sensoterra,soilscout,weenat,farm21,sentek,micasense
server:
  servlet:
    context-path: ${CONTEXT_PATH}
