app:
  version: '@project.version@'
  api-key: ${API_KEY}
  sensors:
    farm21:
      manufacturer: FARM21
      fiwareDeviceIdPrefix: "urn:5gla:iotdevice:farm21:"
      fiwareDeviceMeasurementIdPrefix: "urn:5gla:sensordata:farm21:"
      enabled: false
      url: https://app.farm21.tech/api/v2/public
      username: ${FARM21_USERNAME}
      password: ${FARM21_PASSWORD}
      apiToken: ${FARM21_API_TOKEN}
    soilscout:
      manufacturer: SOIL_SCOUT
      fiwareDeviceIdPrefix: "urn:5gla:iotdevice:soilscout:"
      fiwareDeviceMeasurementIdPrefix: "urn:5gla:sensordata:soilscout:"
      enabled: false
      url: https://soilscouts.fi/api/v1
      username: ${SOILSCOUT_USERNAME}
      password: ${SOILSCOUT_PASSWORD}
    agranimo:
      manufacturer: AGRANIMO
      fiwareDeviceIdPrefix: "urn:5gla:iotdevice:agranimo:"
      fiwareDeviceMeasurementIdPrefix: "urn:5gla:sensordata:agranimo:"
      enabled: false
      url: https://public-staging.agranimo.com
      username: ${AGRANIMO_USERNAME}
      password: ${AGRANIMO_PASSWORD}
    agvolution:
      manufacturer: AGVOLUTION
      fiwareDeviceIdPrefix: "urn:5gla:iotdevice:agvolution:"
      fiwareDeviceMeasurementIdPrefix: "urn:5gla:sensordata:agvolution:"
      enabled: false
      url: https://api.agvolution.com
      username: ${AGVOLUTION_USERNAME}
      password: ${AGVOLUTION_PASSWORD}
    sensoterra:
      manufacturer: SENSOTERRA
      fiwareDeviceIdPrefix: "urn:5gla:iotdevice:sensoterra:"
      fiwareDeviceMeasurementIdPrefix: "urn:5gla:sensordata:sensoterra:"
      enabled: false
      url: https://monitor.sensoterra.com/api/v3
      username: ${SENSOTERRA_USERNAME}
      password: ${SENSOTERRA_PASSWORD}
    micasense:
      manufacturer: MICASENSE
      fiwareDeviceIdPrefix: "urn:5gla:iotdevice:micasense:"
      fiwareDeviceMeasurementIdPrefix: "urn:5gla:sensordata:micasense:"
      enabled: false
      imagePathBaseUrl: ${IMAGE_PATH_BASE_URL}
    sentek:
      manufacturer: SENTEK
      fiwareDeviceIdPrefix: "urn:5gla:iotdevice:sentek:"
      fiwareDeviceMeasurementIdPrefix: "urn:5gla:sensordata:sentek:"
      enabled: true
      url: https://www.irrimaxlive.com/api
      apiToken: ${SENTEK_API_TOKEN}
    weenat:
      manufacturer: WEENAT
      fiwareDeviceIdPrefix: "urn:5gla:iotdevice:weenat:"
      fiwareDeviceMeasurementIdPrefix: "urn:5gla:sensordata:weenat:"
      enabled: true
      url: https://api-prod.weenat.com/api
      username: ${WEENAT_USERNAME}
      password: ${WEENAT_PASSWORD}
  scheduledDataImportCron: "0 */15 * * * *" # every 15 minutes
  fiware:
    contextBrokerUrl: ${CONTEXT_BROKER_URL}
    subscriptions:
      enabled: true
      notificationUrl: ${NOTIFICATION_URL}
logging:
  level:
    root: info
    de.app.fivegla: trace
one:
  microstream:
    storage-directory: ${MICROSTREAM_STORAGE_DIRECTORY}
    channel-count: 2

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
