app:
  api-key: ${API_KEY}
  imagePathBaseUrl: ${IMAGE_PATH_BASE_URL}
  scheduled:
    data-import:
      # Spring Boot uses ISO-8601 durations, https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/Duration.html#parse(java.lang.CharSequence)
      initial-delay: PT10S # 10 seconds
      delay: PT30M # 30 minutes
    daysInThePastForInitialImport: 1
  fiware:
    contextBrokerUrl: ${CONTEXT_BROKER_URL}
    subscriptions:
      enabled: true
      notificationUrls: ${NOTIFICATION_URLS}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  s3:
    endpoint: ${S3_ENDPOINT}
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_KEY}
logging:
  level:
    root: info
    de.app.fivegla: trace
    java.net.http: debug
    hibernate.SQL: debug

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,agranimo,agvolution,sensoterra,soilscout,weenat,farm21,sentek,micasense
server:
  servlet:
    context-path: ${CONTEXT_PATH}

spring:
  data:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USER}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    change-log: db/changelog/db.changelog-master.yml