app:
  version: '@project.version@'
  sensors:
    soilscout:
      url: https://soilscouts.fi/api/v1/
      username: ${SOILSCOUT_USERNAME}
      password: ${SOILSCOUT_PASSWORD}
fiware:
  context-broker-url: ${CONTEXT_BROKER_URL}
logging:
  level:
    root: info
    de.app.fivegla: trace
    one.microstream: debug
one:
  microstream:
    storage-directory: ${MICROSTREAM_STORAGE_DIRECTORY}
    channel-count: 2