scrape_configs:
  - job_name: '5gla-integration-services-actuator'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]