version: "3.7"
services:
  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./.grafana-data:/var/lib/grafana
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./.uptime-kuma-data:/app/data
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    command: '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
volumes:
  grafana-data: { }
  uptime-kuma-data: { }