name: CI

on:
  pull_request:
  merge_group:
    branches:
      - "main"
  push:
    branches:
      - "main"

env:
  FARM21_API_TOKEN: ${{ secrets.FARM21_API_TOKEN }}
  SOILSCOUT_USERNAME: ${{ secrets.SOILSCOUT_USERNAME }}
  SOILSCOUT_PASSWORD: ${{ secrets.SOILSCOUT_PASSWORD }}
  AGRANIMO_USERNAME: ${{ secrets.AGRANIMO_USERNAME }}
  AGRANIMO_PASSWORD: ${{ secrets.AGRANIMO_PASSWORD }}
  SENTEK_API_TOKEN: ${{ secrets.SENTEK_API_TOKEN }}
  AGVOLUTION_USERNAME: ${{ secrets.AGVOLUTION_USERNAME }}
  AGVOLUTION_PASSWORD: ${{ secrets.AGVOLUTION_PASSWORD }}
  SENSOTERRA_USERNAME: ${{ secrets.SENSOTERRA_USERNAME }}
  SENSOTERRA_PASSWORD: ${{ secrets.SENSOTERRA_PASSWORD }}
  MICROSTREAM_STORAGE_DIRECTORY: ./microstream-integration-test
  IMAGE_PATH_BASE_URL: localhost:8080/images
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  build_jdk_17:
    name: Build with Java 17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: microsoft
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B verify --file pom.xml --settings .github/settings.xml