name: CI

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  build_jdk_17:
    name: Build with Java 18
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 18
        uses: actions/setup-java@v2
        with:
          java-version: 18
          distribution: microsoft
      - name: Build with Maven
        run: mvn -B verify --file pom.xml