name: CI

on:
  pull_request:
  merge_group:
    branches:
      - "main"
  push:
    branches:
      - "main"

env:
  FARM21_API_TOKEN: ${{ vars.FARM21_API_TOKEN }}
  SOILSCOUT_USERNAME: ${{ vars.SOILSCOUT_USERNAME }}
  SOILSCOUT_PASSWORD: ${{ vars.SOILSCOUT_PASSWORD
  AGRANIMO_USERNAME: ${{ vars.AGRANIMO_USERNAME }}
  AGRANIMO_PASSWORD: ${{ vars.AGRANIMO_PASSWORD }}
  CONTEXT_BROKER_URL: localhost:5221
  MICROSTREAM_STORAGE_DIRECTORY: ./microstream-integration-test

jobs:
  build_jdk_17:
    name: Build with Java 17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: microsoft
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B verify --file pom.xml --settings .github/settings.xml